image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm init clarity-starter
    command: 'echo "TODO: Replace with command to start project"'
    
vscode:
  extensions:
    - blockstack.clarity@0.0.5:rBhb1NsIYs1/wpFyiyXNdA==
    - lgalabru.clarity-lsp@0.2.66:PEBgheot/B02RfVLfwbzYg==
    - 2gua.rainbow-brackets@0.0.6:Tbu8dTz0i+/bgcKQTQ5b8g==    